# Generated by Django 3.0.6 on 2020-05-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
