# Generated by Django 3.0.6 on 2020-05-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
