# Generated by Django 3.0.6 on 2020-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_remove_stock_stock_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_available',
            field=models.FloatField(null=True),
        ),
    ]
